### ISSUE TITLE
Version Conflicts. Lazy-object-proxy & AIOHTTP

### ISSUE THREAD

**Issue by ghost** [EntropySynthetica/PacDiscordRaidBot#4]
INFO: pip is looking at multiple versions of aiohttp to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 2) and lazy-object-proxy==1.5.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested lazy-object-proxy==1.5.2
    astroid 2.4.2 depends on lazy-object-proxy==1.4.*

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The command '/bin/sh -c python -m pip install -r requirements.txt' returned a non-zero code: 1

Ubuntu 18 & 20. tried both - Attempted to install all manually but it uninstalls AIO and LOP from latest to lower version

**Comment by ghost** [comment]
12/20/2020, 21:07:20 , Channel=roster, Author=Not Reformed#6666, Message=!NewTrial 2 2 8 Vet Atherian Archive Trial s                                                                                                                        ignups
12/20/2020, 21:07:21 , Message from bot, ignoring.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 377, in on_message
    await last_message.add_reaction(emoji)
  File "/usr/local/lib/python3.8/dist-packages/discord/message.py", line 993, in add_reaction
    emoji = self._emoji_reaction(emoji)
![image](https://user-images.githubusercontent.com/71048723/102725755-198e4480-4354-11eb-9289-79401b2d0940.png)

  File "/usr/local/lib/python3.8/dist-packages/discord/message.py", line 1080, in _emoji_reaction
    raise InvalidArgument('emoji argument must be str, Emoji, or Reaction not {.class.name}.'.format(emoji))
discord.errors.InvalidArgument: emoji argument must be str, Emoji, or Reaction not NoneType.


.env has updated Emoji ID's
